title = "HigherCap"
baseURL = "www.highercap.com"
languageCode = "en-us"
themesDir = "../.."
theme = "hugo-serif-theme"

[params]
google_analytics_id = ""
google_tag_manager_id = ""

  [params.logo]
  standard = "images/highercaplogo.png"
  mobile = "images/highercap.png"
  alt = "HigherCap - Business Solutions"

  [params.homepage_meta_tags]
  meta_description = "HigherCap helps maximize a business’s potential by bringing expert technology products and opinions to the table."
  meta_og_title = "HigherCap"
  meta_og_type = "website"
  meta_og_url = "https://www.highercap.com"
  meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
  meta_og_description = "Test what is this"
  meta_twitter_card = "summary"
  meta_twitter_site = "@highercap"
  meta_twitter_creator = "@highercap"

[[menu.main]]
name = "Services"
url = "/services/"
weight = 1

# [[menu.main]]
# name = "Team"
# url = "/team/"
# weight = 2

[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
